//ESTILOS ROTINA

import { StyleSheet } from "react-native";
import  estilosCores from '../../styles/colors.js';
import  estilosFontes from '../../styles/fonts.js';


export const estilosCalc = StyleSheet.create({
    container:{
        width: '100%',
        height: '100%',
        backgroundColor: 'black',
    },
    scroll:{
        width: '100%',
        //maxHeight define a altura do scroll, height não
        maxHeight: '100%',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: estilosCores.branco,
    },
    scroll_content:{
        //ajuste do conteúdo do scroll
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    header:{
        width: '100%',
        height: 120,
        borderBottomEndRadius: 30,
        borderBottomStartRadius: 30,
        backgroundColor: estilosCores.verde_claro,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    menu:{
        position: 'absolute',
        marginTop: 701,
        width: '100%',
        height: 80,
        borderTopStartRadius: 30,
        borderTopEndRadius: 30,
        backgroundColor: estilosCores.verde_escuro,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
    }, 
    btnMenu:{
        position: 'relative',
        width:'15%',
        height: '80%',
        //backgroundColor: 'red',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    imgMenu:{
        position: 'relative',
        width: '50%',
        height: '50%',
    },
    logo:{
        marginTop: 30,
        width: 250,
        height: 100,
    },
    texto:{
        margin: 30,
        textAlign: 'center',
        fontSize: 20,
        fontFamily: estilosFontes.text,
    },
    areaForm:{
        width: '90%',
        height: 500,
        paddingTop: 100,
        backgroundColor: 'white',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    txtInputArea:{
        width: 280, 
        height: 30,
        borderRadius: 20,
        margin: 15,
        backgroundColor: estilosCores.pastel,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    txtInput:{
        width: 240,
        height: 30,
    },
    inputImage:{
        width: 30,
        height: 30,
        borderRadius: 100,
    },
    btnSenha:{
        width: 30,
        height: 30,
    },
    btnPrimary:{
        width: 150,
        height: 45,
        borderRadius: 50,
        marginTop: 15,
        marginLeft: 10,
        marginRight: 10,
        marginBottom: 10,
        backgroundColor: estilosCores.verde_claro,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    btnSecundary:{
        width: 120,
        height: 30,
        borderRadius: 20,
        margin: 10,
        backgroundColor: estilosCores.verde_escuro,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },

    //=============

    scroll_dia:{
        position: 'relative',
        width: '90%',
        maxHeight: '100%',
        height: 350,
        //backgroundColor: 'gray',
        display: 'flex',
        flexDirection: 'row',
    },
    scroll_dia_content:{
        //ajuste do conteúdo do scroll dos dias
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    container_dia:{
        margin: 25,
        width: 350,
        height: 350,
        borderRadius: 20,
        backgroundColor: estilosCores.verde_escuro,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    titulo_dia:{
        position: 'relative',
        //backgroundColor: 'red',
        fontFamily: estilosFontes.heading,
        color: estilosCores.verde_claro,
        width: '100%',
        height: '20%',
        fontSize: 25,
        paddingTop: 15,
        textAlign: 'center',
        //rodando o nome do dia e ajustando espaço com a lista
        transform: [{rotate: '-90deg'}],
        margin: '-40%',
    },
    lista_tarefas:{
        position: 'relative',
        width: '70%',
        height: '100%',
        //backgroundColor: 'blue',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    container_tarefa:{
        position: 'relative',
        width: '90%',
        height: 50,
        //backgroundColor: 'green',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    icon_tarefa:{
        position: 'relative',
        width: '25%',
        height: '100%',
        backgroundColor: 'white',
        borderRadius: 10,
    },
    barr_tarefa:{
        position: 'relative',
        width: '70%',
        height: '100%',
        backgroundColor: 'white',
        borderRadius: 5,
    },
    btnData:{
        position: 'relative',
        width: '70%',
        height: '100%',
        backgroundColor: 'white',
        borderRadius: 5,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    //=============================
    container_select:{
        marginTop: 330,
        marginLeft: 0,
        position: 'absolute',
        width: 393,
        height: 400,
        borderTopRightRadius: 20,
        borderTopLeftRadius: 20,
        backgroundColor: 'rgba(125, 195, 131, 0.9)' ,  //estilosCores.verde_medio,
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-around',
        alignItems: 'flex-start',
    },
    img_select:{
        width: 75,
        height: 75,
    },
    img_tarefa:{
        position: 'relative',
        width: '100%',
        height: '100%',
        borderRadius: 5,
    },
    //==============================================================

    container_calculadora:{
        margin: 0,
        width: 350,
        height: 360,
        borderColor: estilosCores.branco,
        //backgroundColor: 'silver',
        //borderStyle: 'solid',
        borderWidth: 1,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        flexWrap: 'wrap',
    },
    titulo_calculadora:{
        position: 'relative',
        marginLeft: 25,
        marginRight: 35,
        marginTop: 30,
        textAlign: 'center',
    },
    icon_calculadora:{
        position: 'relative',
        width: '10%',
        height: '10%',
        margin: 15,
    },
    input_unidade:{
        position: 'relative',
        width: '20%',
        height: '12%',
        borderRadius: 30,
        margin: 15,
        textAlign: 'center',
    },
    input_periodo:{
        position: 'relative',
        width: '35%',
        height: '12%',
        borderRadius: 30,
        margin: 10,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    picker:{
        position: 'relative',
        width: '100%',
        height: '100%',
        fontSize: 1,
    },
    container_result:{
        width: 300,
        height: 280,
        //backgroundColor: 'black',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        flexWrap: 'wrap',
    },
    result:{
        position: 'relative',
        width: '36%',
        height: '36%',
        margin: 10,
        borderRadius: 20,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
    },
    titulo_result:{
        color: 'white',
        fontWeight: 'bold',
        textAlign: 'center',
        padding: 3,
    },
    container_grafico:{
        marginTop: 0,
        width: 350,
        height: 350,
        backgroundColor: '#e8e8e8',
        borderRadius: 10,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-around',
        alignItems: 'flex-start',
    },
    barra_grafico:{
        position: 'relative',
        minWidth: '20%',
        //width: '50%',
        height: 50,
        backgroundColor: 'green',
        borderTopLeftRadius: 25,
        borderBottomStartRadius: 25,
        borderTopRightRadius: 25,
        borderBottomEndRadius: 25,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    container_pegada:{
        width: 350,
        height: 200,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-around',
        alignItems: 'center',
        marginTop: 20,
        borderRadius: 30,
    }

   

})