//ESTILOS HOME

import { StyleSheet } from "react-native";
import  estilosCores from '../../styles/colors.js';
import  estilosFontes from '../../styles/fonts.js';


export const estilosConfig = StyleSheet.create({
    container:{
        width: '100%',
        height: '100%',
        backgroundColor: 'black',
    },
    subContainer:{
        position: 'relative',
        width: '95%',
        height: 250,
        borderRadius: 15,

        backgroundColor: estilosCores.verde_medio,

        marginTop: 50,
        marginBottom: 25,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    square:{
        width: 150,
        height: 150,
        borderRadius: 20,
        backgroundColor: estilosCores.verde_claro,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    img_square:{
        width: '90%',
        height: '90%',
        borderRadius: 15,
    },
    info_prox_tarefa:{
        position: 'relative',
        width: 180,
        height: '90%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-around',
        alignItems: 'center',
    },
    quest:{
        position: 'relative',
        width: '90%',
        height: 70,
        borderRadius: 5,
        backgroundColor: 'white',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
    },
    quest_icon:{
        position: 'relative',
        width: '20%',
        height: '100%',
        backgroundColor: 'red',
    },
    quest_name:{
        position: 'relative',
        width: '80%',
        height: '100%', 
        paddingTop: 25,
        paddingLeft: 20,
    },
    scroll:{
        width: '100%',
        //maxHeight define a altura do scroll, height não
        maxHeight: '100%',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: estilosCores.branco,
    },
    scroll_content:{
        //ajuste do conteúdo do scroll
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    header:{
        width: '100%',
        height: 120,
        borderBottomEndRadius: 30,
        borderBottomStartRadius: 30,
        backgroundColor: estilosCores.verde_claro,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    menu:{
        position: 'absolute',
        marginTop: 701,
        width: '100%',
        height: 80,
        borderTopStartRadius: 30,
        borderTopEndRadius: 30,
        backgroundColor: estilosCores.verde_escuro,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
    }, 
    btnMenu:{
        position: 'relative',
        width:'15%',
        height: '80%',
        //backgroundColor: 'red',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    imgMenu:{
        position: 'relative',
        width: '50%',
        height: '50%',
    },
    logo:{
        marginTop: 30,
        width: 250,
        height: 100,
    },
    titulo:{
        margin: 10,
        fontSize: 22,
        fontFamily: estilosFontes.text,
        color: 'white',
    },
    areaForm:{
        width: '90%',
        height: 500,
        paddingTop: 100,
        backgroundColor: 'white',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    txtInputArea:{
        width: 280, 
        height: 30,
        borderRadius: 20,
        margin: 15,
        backgroundColor: estilosCores.pastel,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    txtInput:{
        width: 240,
        height: 30,
    },
    inputImage:{
        width: 30,
        height: 30,
        borderRadius: 100,
    },
    btnSenha:{
        width: 30,
        height: 30,
    },
    btnPrimary:{
        width: 150,
        height: 45,
        borderRadius: 50,
        //marginTop: 45,
        //marginLeft: 10,
        //marginRight: 10,
        //marginBottom: 10,
        backgroundColor: estilosCores.verde_claro,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    btnSecundary:{
        width: 120,
        height: 30,
        borderRadius: 20,
        margin: 10,
        backgroundColor: estilosCores.verde_escuro,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    btnCancel:{
        width: 120,
        height: 30,
        borderRadius: 20,
        //margin: 10,
        backgroundColor: estilosCores.Rred,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
   

})